### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by victoriavilasb** [victoriavilasb/ttrack#8]
### Config
- [ ] data storage
  - [x] external DB
  _user can migrate database model, configuring their own database_
  - [ ] blob storage (files)
  - [ ] local file system (files)
   _files should be very small_
- [ ] report and clean routines

### Shortcuts
- [x] save short-cuts for a task (for example: web pages, folders, applications).
```sh
ttrack init shortcut -n coding -o program1,program2 -a github.com,jira.attlassian.com

```
attributes(shortcut name, actions)
The user can decide to open all short-cuts when starting to work on a task.

### Tasks
- [x] pause a task
- [x] continue a task
- [x] start task
- [x] finish task
- [x] add tag
- [x] remove tag
- [x] list tasks _(ttrack ls -t)_

### Interruptions
- [ ] start interruption
- [ ] finish interruption

### Report
- [ ] generate report for a specified time period
- [ ] send report to slack (periodically)

### Project
- [x] create project
- [x] add tasks to project
- [x] list projects _(ttrack ls -p)_
- [x] remove tasks from project
- [x] archive project
- [x] reactivate project
